package bratrax

import (
	"fmt"
	"net/url"
	"os"
	"strconv"
)

// Config holds the Bratrax proxy configuration.
type Config struct {
	// TargetURL is the parsed URL of the Flask API backend.
	TargetURL *url.URL
	// UsersDSN is the PostgreSQL connection string for the rill_users table.
	UsersDSN string
	// IssuerURL is baked into issued JWTs and verified on incoming tokens.
	IssuerURL string
	// AudienceURL is the expected `aud` claim value.
	AudienceURL string
	// RuntimeAddr is the local-loopback address of the in-process Rill HTTP
	// server (e.g. "http://127.0.0.1:9009"). The /bratrax/mcp handler
	// reverse-proxies to this address to reach the runtime's per-instance MCP
	// route. It MUST stay loopback: pointing it at the public URL makes every
	// MCP tool call hairpin back out through DNS/TLS/nginx, so any edge hiccup
	// or restart window surfaces as "upstream MCP server unavailable".
	RuntimeAddr string
	// SecureCookie controls the `Secure` attribute on the auth cookie. Must be
	// true when Rill is served behind HTTPS (e.g. prod).
	SecureCookie bool
	// OnlyInvitationLink, when true, disables the public /bratrax/auth/signup
	// endpoint. Account creation then requires a single-use invitation link
	// generated by a super_admin via /bratrax/superadmins/signup-invite. Toggle
	// to false to restore open public signup. Read from ONLY_INVITATION_LINK.
	OnlyInvitationLink bool

	// AllowWoocommerce, when true, exposes the WooCommerce store connector on
	// /onboard/store and /connectors (otherwise it renders as "coming soon" /
	// is hidden). Surfaced to the frontend via GET /bratrax/auth/config. Read
	// from ALLOW_WOOCOMMERCE; flip per need without a code change.
	AllowWoocommerce bool

	// ShopifyClientID / ShopifyClientSecret are the Shopify app's OAuth
	// credentials, used here only to verify App Bridge session tokens (HS256,
	// signed with the secret, audience = the client id). Both must be set for
	// embedded-admin auth to work; when either is empty the session-token path
	// is disabled and only the bratrax_auth cookie is accepted. Same values
	// Flask reads as SHOPIFY_CLIENT_ID / SHOPIFY_CLIENT_SECRET.
	ShopifyClientID     string
	ShopifyClientSecret string

	// --- Demo-user AI trial ---
	//
	// Demo visitors share one workspace, so they can never bring their own
	// Anthropic key (the key is bound to the instance, and they're viewers).
	// Instead they get a fixed number of AI-sidebar prompts on the platform's
	// own key, then the sidebar locks behind a sign-up CTA.
	//
	// AnthropicAPIKey is the platform key, same value Flask reads as
	// ANTHROPIC_API_KEY. When empty the whole feature is inert and the demo
	// workspace falls back to its stored BYOK key like any other client.
	AnthropicAPIKey string
	// DemoUsersModel overrides the claude driver's default model for the demo
	// instance only (the default is Opus, the priciest option). Empty leaves the
	// driver default in place.
	DemoUsersModel string
	// DemoClientSlug is the clickhouse_db of the shared demo workspace. Must
	// match Flask's DEMO_CLIENT_SLUG.
	DemoClientSlug string
	// DemoUserMaxPrompts is the lifetime AI-prompt budget per demo user. Must
	// match Flask's DEMO_USER_MAX_PROMPTS, which only advertises the number —
	// this is the one that's enforced.
	DemoUserMaxPrompts int
}

// ConfigFromEnv reads Bratrax configuration from environment variables.
func ConfigFromEnv() (*Config, error) {
	raw := os.Getenv("BRATRAX_API_URL")
	if raw == "" {
		raw = "http://localhost:8082"
	}

	u, err := url.Parse(raw)
	if err != nil {
		return nil, fmt.Errorf("bratrax: invalid BRATRAX_API_URL %q: %w", raw, err)
	}

	if u.Scheme != "http" && u.Scheme != "https" {
		return nil, fmt.Errorf("bratrax: BRATRAX_API_URL %q must use http or https scheme", raw)
	}
	if u.Host == "" {
		return nil, fmt.Errorf("bratrax: BRATRAX_API_URL %q must include a host", raw)
	}

	usersDSN := os.Getenv("BRATRAX_USERS_DSN")
	if usersDSN == "" {
		usersDSN = "postgres://airflow:BratMaxPass@localhost:5434/airflow?sslmode=disable"
	}

	issuerURL := os.Getenv("BRATRAX_ISSUER_URL")
	if issuerURL == "" {
		issuerURL = "http://localhost:9009/bratrax"
	}

	audienceURL := os.Getenv("BRATRAX_AUDIENCE_URL")
	if audienceURL == "" {
		audienceURL = "http://localhost:9009"
	}

	// Loopback address of our own Rill HTTP server, used only as the MCP
	// reverse-proxy target. Defaults to the local port; never set this to the
	// public URL (see Config.RuntimeAddr).
	runtimeAddr := os.Getenv("BRATRAX_RUNTIME_ADDR")
	if runtimeAddr == "" {
		runtimeAddr = "http://127.0.0.1:9009"
	}

	secureCookie := false
	if rawSecure := os.Getenv("BRATRAX_SECURE_COOKIE"); rawSecure != "" {
		v, parseErr := strconv.ParseBool(rawSecure)
		if parseErr != nil {
			return nil, fmt.Errorf("bratrax: invalid BRATRAX_SECURE_COOKIE %q: %w", rawSecure, parseErr)
		}
		secureCookie = v
	}

	onlyInvitationLink := false
	if raw := os.Getenv("ONLY_INVITATION_LINK"); raw != "" {
		v, parseErr := strconv.ParseBool(raw)
		if parseErr != nil {
			return nil, fmt.Errorf("bratrax: invalid ONLY_INVITATION_LINK %q: %w", raw, parseErr)
		}
		onlyInvitationLink = v
	}

	allowWoocommerce := false
	if raw := os.Getenv("ALLOW_WOOCOMMERCE"); raw != "" {
		v, parseErr := strconv.ParseBool(raw)
		if parseErr != nil {
			return nil, fmt.Errorf("bratrax: invalid ALLOW_WOOCOMMERCE %q: %w", raw, parseErr)
		}
		allowWoocommerce = v
	}

	demoClientSlug := os.Getenv("DEMO_CLIENT_SLUG")
	if demoClientSlug == "" {
		demoClientSlug = "dummy"
	}

	demoUserMaxPrompts := 10
	if raw := os.Getenv("DEMO_USER_MAX_PROMPTS"); raw != "" {
		v, parseErr := strconv.Atoi(raw)
		if parseErr != nil {
			return nil, fmt.Errorf("bratrax: invalid DEMO_USER_MAX_PROMPTS %q: %w", raw, parseErr)
		}
		if v < 0 {
			return nil, fmt.Errorf("bratrax: DEMO_USER_MAX_PROMPTS must not be negative, got %d", v)
		}
		demoUserMaxPrompts = v
	}

	return &Config{
		TargetURL:           u,
		UsersDSN:            usersDSN,
		IssuerURL:           issuerURL,
		AudienceURL:         audienceURL,
		RuntimeAddr:         runtimeAddr,
		SecureCookie:        secureCookie,
		OnlyInvitationLink:  onlyInvitationLink,
		AllowWoocommerce:    allowWoocommerce,
		ShopifyClientID:     os.Getenv("SHOPIFY_CLIENT_ID"),
		ShopifyClientSecret: os.Getenv("SHOPIFY_CLIENT_SECRET"),
		AnthropicAPIKey:     os.Getenv("ANTHROPIC_API_KEY"),
		DemoUsersModel:      os.Getenv("DEMO_USERS_MODEL"),
		DemoClientSlug:      demoClientSlug,
		DemoUserMaxPrompts:  demoUserMaxPrompts,
	}, nil
}
