import type { ConnectionCategory, PlatformConfig } from "./types";

export const PLATFORMS: PlatformConfig[] = [
  // ── Advertising ──
  {
    id: "facebook",
    name: "Facebook Ads",
    logo: "fb-logo.webp",
    description: "Connect your Facebook ad accounts for campaign tracking",
    category: "advertising",
    flowType: "client-sdk",
    apiSlug: "facebook",
    callbackParams: [],
    connectionKey: "Facebook",
    detailType: "ad",
  },
  {
    id: "google-ads",
    name: "Google Ads",
    logo: "google-ads-logo.svg",
    description: "Connect your Google Ads accounts for campaign tracking",
    category: "advertising",
    flowType: "client-sdk",
    apiSlug: "google",
    callbackParams: [],
    connectionKey: "Google",
    detailType: "ad",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    logo: "pinterest-logo.png",
    description: "Connect your Pinterest ad account for campaign tracking",
    category: "advertising",
    flowType: "oauth-redirect",
    apiSlug: "pinterest",
    callbackParams: ["code"],
    connectionKey: "Pinterest",
    detailType: "ad",
  },
  {
    id: "amazon-ads-us",
    name: "Amazon Ads (US)",
    logo: "amazon-ads-logo.png",
    description: "Connect your Amazon Ads account (North America)",
    category: "advertising",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon-ads",
    callbackParams: ["code", "state"],
    connectionKey: "Amazon Ads",
    detailType: "ad",
    regions: ["us"],
  },
  {
    id: "amazon-ads-eu",
    name: "Amazon Ads (EU)",
    logo: "amazon-ads-logo.png",
    description: "Connect your Amazon Ads account (Europe)",
    category: "advertising",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon-ads",
    callbackParams: ["code", "state"],
    connectionKey: "Amazon Ads",
    detailType: "ad",
    regions: ["eu"],
  },
  {
    id: "amazon-ads-fe",
    name: "Amazon Ads (FE)",
    logo: "amazon-ads-logo.png",
    description: "Connect your Amazon Ads account (Far East)",
    category: "advertising",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon-ads",
    callbackParams: ["code", "state"],
    connectionKey: "Amazon Ads",
    detailType: "ad",
    regions: ["fe"],
  },
  {
    id: "tiktok-ads",
    name: "TikTok Ads",
    logo: "tiktok-logo.png",
    description: "Connect your TikTok ad account for campaign tracking",
    category: "advertising",
    flowType: "oauth-redirect",
    apiSlug: "tiktok-ads",
    callbackParams: ["code", "state"],
    connectionKey: "TikTok",
    detailType: "ad",
  },
  {
    id: "bing-ads",
    name: "Microsoft Bing Ads",
    logo: "bing-ads-logo.webp",
    description: "Connect Microsoft Advertising for Bing/MSN campaign tracking",
    category: "advertising",
    flowType: "oauth-redirect",
    apiSlug: "bing-ads",
    callbackParams: ["code", "state"],
    connectionKey: "Bing Ads",
    detailType: "ad",
  },
  {
    id: "taboola",
    name: "Taboola",
    logo: "taboola-logo.png",
    description: "Connect your Taboola native advertising account",
    category: "advertising",
    flowType: "oauth-redirect",
    apiSlug: "taboola",
    callbackParams: ["code"],
    connectionKey: "Taboola",
    detailType: "ad",
  },
  {
    id: "outbrain",
    name: "Outbrain",
    logo: "outbrain-logo.png",
    description: "Connect your Outbrain native advertising account",
    category: "advertising",
    flowType: "credential-modal",
    apiSlug: "outbrain",
    callbackParams: [],
    connectionKey: "Outbrain",
    detailType: "ad",
  },

  // ── E-commerce ──
  {
    id: "shopify",
    name: "Shopify",
    logo: "shopify-logo.webp",
    description: "Connect your Shopify store for e-commerce analytics",
    category: "ecommerce",
    flowType: "oauth-modal-input",
    apiSlug: "shopify",
    callbackParams: ["code", "shop", "hmac"],
    connectionKey: "Shopify",
    detailType: "crm",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    logo: "woocommerce-logo.png",
    description: "Connect your WooCommerce store for e-commerce analytics",
    category: "ecommerce",
    flowType: "oauth-modal-input",
    apiSlug: "woocommerce",
    callbackParams: [],
    connectionKey: "WooCommerce",
    detailType: "crm",
  },
  {
    id: "amazon-sp-us",
    name: "Amazon SP (US)",
    logo: "amazon-logo.webp",
    description: "Connect Amazon Seller Central (North America)",
    category: "ecommerce",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon",
    callbackParams: ["spapi_oauth_code", "selling_partner_id"],
    connectionKey: "Amazon",
    detailType: "crm",
    regions: ["us"],
  },
  {
    id: "amazon-sp-eu",
    name: "Amazon SP (EU)",
    logo: "amazon-logo.webp",
    description: "Connect Amazon Seller Central (Europe)",
    category: "ecommerce",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon",
    callbackParams: ["spapi_oauth_code", "selling_partner_id"],
    connectionKey: "Amazon",
    detailType: "crm",
    regions: ["eu"],
  },
  {
    id: "amazon-sp-fe",
    name: "Amazon SP (FE)",
    logo: "amazon-logo.webp",
    description: "Connect Amazon Seller Central (Far East)",
    category: "ecommerce",
    flowType: "oauth-redirect-region",
    apiSlug: "amazon",
    callbackParams: ["spapi_oauth_code", "selling_partner_id"],
    connectionKey: "Amazon",
    detailType: "crm",
    regions: ["fe"],
  },
  {
    id: "stripe",
    name: "Stripe",
    logo: "stripe-logo.webp",
    description: "Connect your Stripe account for payment analytics",
    category: "ecommerce",
    flowType: "oauth-redirect",
    apiSlug: "stripe",
    callbackParams: ["code"],
    connectionKey: "Stripe",
    detailType: "crm",
  },

  // ── CRM / Marketing ──
  {
    id: "gohighlevel",
    name: "GoHighLevel",
    logo: "ghl-logo.svg",
    description: "Connect your GoHighLevel CRM account",
    category: "crm",
    flowType: "oauth-redirect",
    apiSlug: "gohighlevel",
    callbackParams: ["code"],
    connectionKey: "GoHighLevel",
    detailType: "crm",
  },
  {
    id: "clickfunnels2",
    name: "ClickFunnels 2",
    logo: "cf-logo.png",
    description: "Connect your ClickFunnels 2 workspace",
    category: "crm",
    flowType: "oauth-redirect",
    apiSlug: "clickfunnels2",
    callbackParams: ["code"],
    connectionKey: "ClickFunnels2",
    detailType: "crm",
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    logo: "klaviyo-logo.png",
    description: "Connect your Klaviyo email marketing account",
    category: "crm",
    flowType: "oauth-redirect",
    apiSlug: "klaviyo",
    callbackParams: ["code", "state"],
    connectionKey: "Klaviyo",
    detailType: "crm",
  },

  // ── Analytics ──
  {
    id: "ga4",
    name: "Google Analytics 4",
    logo: "ga4-logo.webp",
    description: "Connect your GA4 property for web analytics",
    category: "analytics",
    flowType: "oauth-redirect",
    apiSlug: "ga4",
    callbackParams: ["code"],
    connectionKey: "GA4",
    detailType: "none",
  },
];

export function getPlatform(id: string): PlatformConfig | undefined {
  return PLATFORMS.find((p) => p.id === id);
}

export function getPlatformsByCategory(
  category: ConnectionCategory,
): PlatformConfig[] {
  return PLATFORMS.filter((p) => p.category === category);
}

export const CATEGORY_LABELS: Record<ConnectionCategory, string> = {
  advertising: "Advertising",
  ecommerce: "E-commerce",
  crm: "CRM / Marketing",
  analytics: "Analytics",
};

export const CATEGORY_ORDER: ConnectionCategory[] = [
  "advertising",
  "ecommerce",
  "crm",
  "analytics",
];
